inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'coverage/**/*'
    - 'test/dummy/tmp/**/*'
    - 'test/dummy/log/**/*'

# Offense count: 130
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: when_needed, always, never
#
# Description from Rubocop Manual:
#   This cop is designed to help upgrade to Ruby 3.0. It will add the comment
#   `# frozen_string_literal: true` to the top of files to enable frozen string
#   literals. Frozen string literals may be default in Ruby 3.0. The comment
#   will be added below a shebang and encoding comment. The frozen string
#   literal comment is only valid in Ruby 2.3+.
#
# https://rubocop.readthedocs.io/en/latest/cops_style/#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 34
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
#
# Description from Rubocop Manual:
# https://rubocop.readthedocs.io/en/latest/cops_style/#styleclassandmodulechildren
Style/ClassAndModuleChildren:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, UseHashRocketsWithSymbolValues,
#   PreferHashRocketsForNonAlnumEndingSymbols.
# SupportedStyles: ruby19, hash_rockets, no_mixed_keys, ruby19_no_mixed_keys
#
# Description from Rubocop Manual:
#   This cop checks hash literal syntax
#
# https://rubocop.readthedocs.io/en/latest/cops_style/#stylehashsyntax
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, MinSize.
# SupportedStyles: percent, brackets
#
# Description from Rubocop Manual:
#   Check for array literals made up of symbols that are not using
#   the `%i()` syntax.
#
# https://rubocop.readthedocs.io/en/latest/cops_style/#stylesymbolarray
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent
  MinSize: 3

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  inherit_mode:
    merge:
      - Exclude
      - ExcludedMethod
  Exclude:
    - 'lib/devise_token_auth/engine.rb'
    - 'test/dummy/config/**/*'
    - 'test/dummy/db/**/*'
  ExcludedMethods:
    - describe
    - draw
    - namespace
    - devise_scope
    - unnest_namespace
  Max: 25

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  inherit_mode:
    merge:
      - Exclude
  Exclude:
    - 'test/**/*'
    - 'Guardfile'
    - 'devise_token_auth.gemspec'
  IgnoredPatterns:
    - '(\A|\s)#'
  Max: 80