inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'coverage/**/*'

# Offense count: 130
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: when_needed, always, never
#
# Description from Rubocop Manual:
#   This cop is designed to help upgrade to Ruby 3.0. It will add the comment
#   `# frozen_string_literal: true` to the top of files to enable frozen string
#   literals. Frozen string literals may be default in Ruby 3.0. The comment
#   will be added below a shebang and encoding comment. The frozen string
#   literal comment is only valid in Ruby 2.3+.
#
# https://rubocop.readthedocs.io/en/latest/cops_style/#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 34
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
#
# Description from Rubocop Manual:
# https://rubocop.readthedocs.io/en/latest/cops_style/#styleclassandmodulechildren
Style/ClassAndModuleChildren:
  Enabled: false